global:
    resolve_timeout: 1m
    slack_api_url: "https://hooks.slack.com/services/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"

route:
    receiver: "slack"

receivers:
    - name: "slack"
      slack_configs:
      - channel: "#alerts"
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: "Alert is firing"
        text: |-
            {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
                *Description:* {{ .Annotations.description }}
                *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
            {{ end }}